---
# https://taskfile.dev

version: '3'

tasks:

  deps:
    desc: Install all Ansible Galaxy requirements
    cmds:
      - ansible-galaxy role install --force-with-deps --keep-scm-meta -r roles/requirements.yaml

  run:docker:
    desc: Run Docker role
    cmds:
      - ansible-playbook docker.yaml

...
